package models.softtech.controls;

public enum SoftTechControlsJourney {
  SOFTWARE_CATEGORY,
  SOFTWARE_RELATED_TO_A_PHYSICAL_GOOD,
  SOFTWARE_CATCHALL,
  TECHNOLOGY_CATEGORY,
  TECHNOLOGY_RELATED_TO_A_PHYSICAL_GOOD,
  TECHNOLOGY_CATCHALL
}
