package models.softtech;

public enum ControlsRelatedToPhysicalGoodsFlow {
  SOFT_TECH_CONTROL_ONE,
  SOFT_TECH_CONTROL_GREATER_THAN_ONE,
  SOFT_TECH_CONTROL_CATCHALL_ZERO,
  SOFT_TECH_CONTROL_CATCHALL_CONTROL_GREATER_THAN_ZERO,
}
