package models.softtech;

public enum ControlsRelatedToPhysicalGoodsFlow {
  SOFTWARE_CONTROL_ONE,
  SOFTWARE_CONTROL_GREATER_THAN_ONE,
  SOFTWARE_CONTROL_CATCHALL_ZERO,
  SOFTWARE_CONTROL_CATCHALL_CONTROL_GREATER_THAN_ZERO,
}
