package models.softtech;

public enum SoftwareExemptionsFlow {
  Q1_EXEMPTIONS_APPLY,
  Q1_EXEMPTIONS_DO_NOT_APPLY,
  Q1_AND_Q2_EXEMPTIONS_APPLY,
  DUAL_USE,
  MILITARY_ZERO_CONTROLS,
  MILITARY_ONE_CONTROL,
  MILITARY_GREATER_THAN_ONE_CONTROL
}
