package models;

public enum ControlCodeFlowStage {
  ADDITIONAL_SPECIFICATIONS,
  BACK_TO_SEARCH,
  BACK_TO_SEARCH_RESULTS,
  CONFIRMED,
  DECONTROLS,
  NOT_APPLICABLE,
  SEARCH_AGAIN,
  TECHNICAL_NOTES
}
