package models;

public enum ControlCodeFlowStage {
  ADDITIONAL_SPECIFICATIONS,
  BACK_TO_SEARCH,
  BACK_TO_RESULTS,
  BACK_TO_MATCHES,
  BACK_TO_CATEGORY,
  CONFIRMED,
  DECONTROLS,
  NOT_APPLICABLE,
  TECHNICAL_NOTES
}
