package models;

public enum VirtualEUOgelStage {
  NO_VIRTUAL_EU,
  VIRTUAL_EU_WITHOUT_CONDITIONS,
  VIRTUAL_EU_WITH_CONDITIONS,
  VIRTUAL_EU_CONDITIONS_DO_APPLY,
  VIRTUAL_EU_CONDITIONS_DO_NOT_APPLY,
}
